### ISSUE TITLE
node_modules/@types/react-native/index.d.ts(8731,18): error TS2717: Subsequent property declarations must have the same type

### ISSUE THREAD

**Issue by AbelHuai** [Microsoft/TypeScript-React-Native-Starter#36]
node_modules/@types/react-native/index.d.ts(8731,18): error TS2717: Subsequent property declarations must have the same type.  Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.

**Comment by chrisbenincasa** [comment]
There's some more discussion about this on this issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24573

**Comment by AbelHuai** [comment]
"skipLibCheck": true or "typescript": "2.7.2"

**Comment by byassine52** [comment]
Thanks a lot @AbelHuai, this fixed it for me❗️👍
